name: LoftJump
main: com.KoryuObihiro.bukkit.loftjump.LoftJump
version: 0.0
authors: [KoryuObihiro]
description: |
    Give yourself some windfall with LoftJump.

commands:
  loftjump:
    aliases: [lj]
    description: Activates LoftJump
    usage: |
           /<command> | Toggles LoftJump
