name: LoftJump
main: com.KoryuObihiro.bukkit.loftjump.LoftJump
version: 1.2
authors: [KoryuObihiro]
description: |
    Give yourself some windfall with LoftJump.
commands:
  loftjump:
    aliases: [ljump, lj]
    description: Allows control of PowerSigns.
    usage: |
           /<command> 