name: LoftJump
main: com.KoryuObihiro.bukkit.loftjump.LoftJump
version: 2.0
authors: [KoryuObihiro]
description: |
    Give yourself some windfall with LoftJump.
commands:
  loftjump:
    aliases: [ljump, lj]
    description: Use LJ-specific commands
    usage: |
           /<command> 